/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import 'stencil-apollo';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppLogin {}
  interface AppLoginAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppSignup {}
  interface AppSignupAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppLogin': Components.AppLogin;
    'AppRoot': Components.AppRoot;
    'AppSignup': Components.AppSignup;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-login': Components.AppLoginAttributes;
    'app-root': Components.AppRootAttributes;
    'app-signup': Components.AppSignupAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {}
  var HTMLAppLoginElement: {
    prototype: HTMLAppLoginElement;
    new (): HTMLAppLoginElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSignupElement extends Components.AppSignup, HTMLStencilElement {}
  var HTMLAppSignupElement: {
    prototype: HTMLAppSignupElement;
    new (): HTMLAppSignupElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-login': HTMLAppLoginElement
    'app-root': HTMLAppRootElement
    'app-signup': HTMLAppSignupElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-login': HTMLAppLoginElement;
    'app-root': HTMLAppRootElement;
    'app-signup': HTMLAppSignupElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
